define(["require", "exports", "tslib", "./validators/email.validator", "./validators/max.validator", "./validators/maxLength.validator", "./validators/min.validator", "./validators/min.validator", "./validators/range.validator", "./validators/rangeLength.validator", "./validators/required.validator", "./validators/regExp.validator", "./validators", "./FormUpdate"], function (require, exports, tslib_1, email_validator_1, max_validator_1, maxLength_validator_1, min_validator_1, min_validator_2, range_validator_1, rangeLength_validator_1, required_validator_1, regExp_validator_1, validators_1, FormUpdate_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    email_validator_1 = tslib_1.__importDefault(email_validator_1);
    max_validator_1 = tslib_1.__importDefault(max_validator_1);
    maxLength_validator_1 = tslib_1.__importDefault(maxLength_validator_1);
    min_validator_1 = tslib_1.__importDefault(min_validator_1);
    min_validator_2 = tslib_1.__importDefault(min_validator_2);
    range_validator_1 = tslib_1.__importDefault(range_validator_1);
    rangeLength_validator_1 = tslib_1.__importDefault(rangeLength_validator_1);
    required_validator_1 = tslib_1.__importDefault(required_validator_1);
    regExp_validator_1 = tslib_1.__importDefault(regExp_validator_1);
    exports.emailValidator = email_validator_1.default;
    exports.maxValidator = max_validator_1.default;
    exports.maxLengthValidator = maxLength_validator_1.default;
    exports.minValidator = min_validator_1.default;
    exports.minLengthValidator = min_validator_2.default;
    exports.rangeValidator = range_validator_1.default;
    exports.rangeLengthValidator = rangeLength_validator_1.default;
    exports.requiredValidator = required_validator_1.default;
    exports.regExpValidator = regExp_validator_1.default;
    exports.Subject = validators_1.Subject;
    exports.Form = FormUpdate_1.FormUpdateVersion;
});
